### PR TITLE
Bioimage export

### PR DESCRIPTION
**Pull request by jdeschamps**
Branch from @mese79

I open it here so that we can make some comments.

### CODE REVIEW

**Comment by jdeschamps** [comment]
This branch depends on https://github.com/CAREamics/careamics-restoration/pull/46 and https://github.com/CAREamics/careamics-restoration/pull/48

**Comment by jdeschamps** [comment]
Is this ready for review? :)

**Comment by mese79** [comment]
> Is this ready for review? :)

I guess it's ready now, until next bug/issue! 😁

**Comment by jdeschamps** [comment]
Since I opened the PR, I can't review it. ^^

I will close it, can you create a PR from this branch?

**Pull request closed without merging**
